### PR TITLE
accept stdin and output to stdout

### LINKED ISSUE #43: Support for schemas by URLs
Would you be interested in supporting passing in a URL as opposed to only a filename?

That way, we could do something like:

```
gpl2ts http://example.com/graphql
```

and get our generated types.

https://www.npmjs.com/package/fetch-graphql-schema supports taking a URL and returning JSON, so most of the work is already done.

I'd be willing to do a PR if this was something you were interested in. For now, I can do it in 2 steps (use the mentioned package to create the file, and then pass that file as input), but it'd be a lot nicer in our workflow to not have to create the intermediate file.

### PR DESCRIPTION
**Pull request by brettjurgens**
partially fixes #43

### CODE REVIEW

**Comment by CWSpear** [comment]
This is similar to what I was trying to do, but I couldn't get `commander` to call its `action` callback. I like what you did with just getting the args from the `program`... I didn't realize you could do that ;-)

One thing I might suggest is leaving it as it is in terms the file name, and just automatically do what it does now if nothing's coming in from `stdin`, otherwise use `stdin`'s input and ignore the file name...

i.e.

```js
const run = (schema, options) => {
    if (!schema) {
        program.outputHelp();
    }

    let interfaces = interfaceUtils.schemaToInterfaces(schema, options);

    let namespace = namespaceUtils.generateNamespace(options.namespace, interfaces);

    if (options.outputFile) {
        namespaceUtils.writeNamespaceToFile(options.outputFile, namespace);
    } else {
        console.log(namespace);
    }
};

if (process.stdin.isTTY) {
    const fileName = program.args[0];
    
    if (!fileName) {
        program.outputHelp();
        process.exit(1);
    }

    const schema = fileIO.readFile(fileName);
    run(schema, program);
} else {
    let input = '';
    process.stdin.resume();
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (data) => input += data);
    process.stdin.on('end', () => {
        if (!input) {
            program.outputHelp();
            process.exit(1);
        }
        run(JSON.parse(input), program)
    });
}
```

I don't normally see CLI tools require a flag to input from `stdin`. The `isTTY` _should_ be good enough for most cases. I do think there are some issues with if you were to try to run this script as a child process or something like that that I was reading. There may be other ways to do it, i.e. I think it'd work if you always read `stdin` and see if input is empty, etc, like so:

```js
let input = '';
process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin.on('data', (data) => input += data);
process.stdin.on('end', () => {
    if (!input) {
        const fileName = program.args[0];

        if (!fileName) {
            program.outputHelp();
            process.exit(1);
        }

        const schema = fileIO.readFile(fileName);
        run(schema, program);
    } else {
        run(JSON.parse(input), program)
    }
});
```

**Comment by CWSpear** [comment]
But yeah, otherwise, this look awesome! Thanks for this. And really, I'd be good either way. It's your project. Just my 2¢

**Comment by CWSpear** [comment]
And probably needs to bump to `0.6` since `-o` being no longer optional to get a file for output is a breaking change.

**Comment by brettjurgens** [comment]
@CWSpear I initially tried using `isTTY` and a bunch of other iterations of trying to get both to work without an argument, but couldn't find a way to make it work 😞 .

will definitely have to bump the version, but i typically do that in a separate PR

**Comment by CWSpear** [comment]
Awesome! Glad you got it to work. 👍 

Looks good. Thanks for this.

**Pull request merged**
