### PR TITLE
[wip] Resolver Generator

### PR DESCRIPTION
**Pull request by brettjurgens**
Starting point for fixing #59

### CODE REVIEW

**Comment by zephraph** [comment]
So what's the plan? I'll definitely jump in and help out. I was kind of surprised to see that you put it in a new package. Wouldn't this be apart of `from-schema`?

Anyway, I'm excited to see it started! This will really help ensure that the revolvers are in parity with the schema.

**Comment by brettjurgens** [comment]
@zephraph still not sure if it should be a part of `from-schema` or not. i'm thinking it's a different use case.

I'm still assessing how to go about this, so I decided to do it separately. however, it's not out of the question that i merge it into the other.

**Comment by tonyxiao** [comment]
@brettjurgens do you have @zephraph do you guys have any updates here?

**Comment by brettjurgens** [comment]
@tonyxiao i do not, unfortunately, have an update. I haven't had much time to work on this, but would love to circle back to it soon

**Comment by brettjurgens** [comment]
replaced with #148

**Pull request closed without merging**
