### PR TITLE
allow graphql schema as an input on cli

### LINKED ISSUE #93: Read schema from .graphql schema file/stdin instead of from JSON
This would be a nice convenience feature.

### PR DESCRIPTION
**Pull request by brettjurgens**
fixes #93

### CODE REVIEW

**Comment by felixfbecker** [comment]
Checked out the branch, but not sure what to do to build. Do I need to run `npm install` in every package subfolder, and `tsc`? Do I need to install and run lerna? It would be great to have some contribution guides in the readme

**Comment by brettjurgens** [comment]
@felixfbecker sorry, i'll add those. going to move to yarn workspaces, which should simplify things.

to build locally and install globally:
```sh
$ lerna bootstrap --hoist graphql
$ cd packages/cli
$ npm i -g .
```

**Comment by felixfbecker** [comment]
And I assume `npm i -g lerna`?
Can I use `npm link` instead of `npm i -g .`?
It fails for me with
```
src/index.ts(9,3): error TS2305: Module '"/Users/felix/git/gql2ts/packages/cli/node_modules/@gql2ts/util/dist/index"' has no exported member 'safeJSONParse'.
```

**Comment by brettjurgens** [comment]
that's strange...

i'll clone fresh and try to work through that, while writing a contribution guide.

in the meantime, can you try installing `gql2ts@1.3.0-alpha.c9e04a1e` ?

**Comment by felixfbecker** [comment]
Seems to work fine! I think there is some help on this missing in the `--help` output though. Looking forward to see this merged

**Comment by felixfbecker** [comment]
Is this missing anything from getting merged?

**Comment by brettjurgens** [comment]
Nope

**Comment by felixfbecker** [comment]
nice, could you cut a release?

**Comment by brettjurgens** [comment]
@felixfbecker just released 1.3.0

**Pull request merged**
